DROP TABLE MEMBER PURGE;

CREATE TABLE MEMBER(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(12) UNIQUE NOT NULL,
	ADDR VARCHAR2(50) NOT NULL,
	NATION VARCHAR2(12) NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	AGE NUMBER NULL
);

CREATE SEQUENCE MEMBER_ID_SEQ;
